/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.udf.ProvaA1_Aviao.UI;

import br.udf.ProvaA1_Aviao.DTO.AviaoDTO;
import br.udf.ProvaA1_Aviao.DAL.AviaoDAL;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rapha
 */
public class frmAviao extends javax.swing.JFrame {

    // instanciando a classe AviaoDTO do pacote DTO e criando seu objeto avião
    AviaoDTO aviao = new AviaoDTO();
    // Instancia a classe AviaoDAL
    AviaoDAL dal = new AviaoDAL();

    public frmAviao() {
        initComponents();
        inserirIcone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigoAvi = new javax.swing.JTextField();
        btnPesquisarAviID = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFabricanteAvi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModeloAvi = new javax.swing.JTextField();
        btnIncluirAvi = new javax.swing.JButton();
        btnAlterarAvi = new javax.swing.JButton();
        btnMostrarTodosAvi = new javax.swing.JButton();
        btnExcluirAvi = new javax.swing.JButton();
        btnLimparAvi = new javax.swing.JButton();
        btnSairAvi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgvAviao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        btnPesquisarAviID.setText("Pesquisar");
        btnPesquisarAviID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarAviIDMouseClicked(evt);
            }
        });
        btnPesquisarAviID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarAviIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Fabricante");

        jLabel3.setText("Modelo");

        txtModeloAvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloAviActionPerformed(evt);
            }
        });

        btnIncluirAvi.setText("Incluir");
        btnIncluirAvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirAviActionPerformed(evt);
            }
        });

        btnAlterarAvi.setText("Alterar");
        btnAlterarAvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarAviActionPerformed(evt);
            }
        });

        btnMostrarTodosAvi.setText("Mostrar Todos");
        btnMostrarTodosAvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosAviActionPerformed(evt);
            }
        });

        btnExcluirAvi.setText("Excluir");
        btnExcluirAvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAviActionPerformed(evt);
            }
        });

        btnLimparAvi.setText("Limpar");
        btnLimparAvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparAviActionPerformed(evt);
            }
        });

        btnSairAvi.setText("Sair");
        btnSairAvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairAviActionPerformed(evt);
            }
        });

        dgvAviao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Aviao ID", "Fabricante", "Modelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dgvAviao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFabricanteAvi)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigoAvi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarAviID))
                            .addComponent(txtModeloAvi, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIncluirAvi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterarAvi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluirAvi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMostrarTodosAvi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimparAvi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSairAvi))
                            .addComponent(jScrollPane1))
                        .addGap(0, 216, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoAvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarAviID))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFabricanteAvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtModeloAvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirAvi)
                    .addComponent(btnAlterarAvi)
                    .addComponent(btnMostrarTodosAvi)
                    .addComponent(btnExcluirAvi)
                    .addComponent(btnLimparAvi)
                    .addComponent(btnSairAvi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloAviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloAviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloAviActionPerformed


    private void btnIncluirAviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirAviActionPerformed
        try {
            //Chama o método abrirBD da classe AviãoDAL
            dal.abrirBD();
            aviao.setAviFabricante(txtFabricanteAvi.getText());
            aviao.setAviModelo(txtModeloAvi.getText());

            // fazendo a validação dos dados
            if (txtFabricanteAvi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo Fabricante do Avião está vazio !!!!");
                txtFabricanteAvi.requestFocus();
            } else if (txtModeloAvi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo Modelo do Avião está vazio !!!!");
                txtModeloAvi.requestFocus();
            } else {
                try {
                    //Chama o método incluirAviao da classe AviaoDAL
                    dal.incluirAviao(aviao);
                    JOptionPane.showMessageDialog(null, "Avião " + txtModeloAvi.getText() + " incluído com sucesso! ");
                    //Chama o método fecharBD da classe AviãoDAL
                    dal.fecharBD();
                    //Limpa os dados preenchidos nos campos de texto
                    txtFabricanteAvi.setText("");
                    txtModeloAvi.setText("");
                    txtFabricanteAvi.requestFocus();
                    btnMostrarTodosAvi.setEnabled(true);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erro Na Conexão. Verifique com o Administrador do Banco de Dados !!!!");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "O campo Modelo do avião está vazio !!!!");
            txtModeloAvi.requestFocus();
        }
    }//GEN-LAST:event_btnIncluirAviActionPerformed

    private void btnPesquisarAviIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarAviIDActionPerformed

        //Verifica se o código do aviao está vazio
        if ("".equals(txtCodigoAvi.getText())) {
            JOptionPane.showMessageDialog(null, "Código do Avião não pode ser vazio, favor digite um código válido !!!!");
            //Após a mensagem de erro, o foco do cursor vai ficar no campo Código do Aviao 
            txtCodigoAvi.requestFocus();
        } else {
            //Faz o tratamento de erro, para verificar se a tabela Avião está vazia
            //O botão Incluir vai ficar dsesabilitado
            btnIncluirAvi.setEnabled(false);
            //O botão Alterar vai ficar habilitado
            btnAlterarAvi.setEnabled(true);
            //O botão Excluir vai ficar habilitado
            btnExcluirAvi.setEnabled(true);
            //O botão Mostrar Todos vai ficar habilitado
            btnMostrarTodosAvi.setEnabled(true);
            //Mostra os dados do aviao pelo seu código
            txtFabricanteAvi.setText(aviao.getAviFabricante());
            txtModeloAvi.setText(aviao.getAviModelo());
            try {
                //Chama o método selecionarAviaoPorID da classe AviaoDAL
                aviao = dal.selecionarAviaoPorID(Integer.valueOf(txtCodigoAvi.getText()));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Avião Não Encontrado. Favor Tente Novamente !!!!");
                txtCodigoAvi.setText(null);
                txtCodigoAvi.requestFocus();
            }
        }
    }//GEN-LAST:event_btnPesquisarAviIDActionPerformed

    private void btnExcluirAviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAviActionPerformed
        aviao.setAviID(Long.parseLong(txtCodigoAvi.getText()));
        Object[] opcoes = {"Sim", "Não"};
        int contador = JOptionPane.showOptionDialog(null, "Deseja Excluir Este Avião: " + txtModeloAvi.getText() + "?",
                "Exclusão", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
        if (contador == JOptionPane.YES_OPTION) {
            try {
                //Chama o método abrirBD da classe AviaoDAL            
                dal.abrirBD();
                //Chama o método excluirAviao da classe AviaoDAL 
                dal.excluirAviao(Integer.valueOf(txtCodigoAvi.getText()));
                JOptionPane.showMessageDialog(null, "Avião Excluído com Sucesso !!!!");
                //apaga os dados preenchidos nos campos de texto abaixo
                txtCodigoAvi.setText(null);
                txtFabricanteAvi.setText("");
                txtModeloAvi.setText("");
                txtCodigoAvi.requestFocus();
                //Chama o método fecharBD da classe AviaoDAL
                dal.fecharBD();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro Na Conexão. Verifique com o Administrador do Banco de Dados !!!!");
            }
        }
    }//GEN-LAST:event_btnExcluirAviActionPerformed

    private void btnMostrarTodosAviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosAviActionPerformed
        //Limpa todas as caixas de texto
        txtFabricanteAvi.setText("");
        txtModeloAvi.setText("");

        //Cria a lista de todos os avioes dentro da tabela aviao
        List<AviaoDTO> selecionaTodosAviao = new ArrayList<>();
        try {
            //Chama o método abrirBD da classe AviaoDAL            
            dal.abrirBD();
            //Chama o m�todo selecionaTodosAviao da Classe AviaoDAL e preeche o mesmo com a lista de todos os avioes.
            selecionaTodosAviao = dal.selecionarListaAviao();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro Na Conexão. Verifique com o Administrador do Banco de Dados !!!!");
        }
        //Prepara a tabela para receber os dados da busca(Lista)
        DefaultTableModel tabm = (DefaultTableModel) dgvAviao.getModel();
        for (int contador = tabm.getRowCount() - 1; contador >= 0; contador--) {
            tabm.removeRow(contador);
        }
        int contador = 0;
        for (AviaoDTO aviao : selecionaTodosAviao) {
            //Mostra as informa��es dentro da Tabela
            tabm.addRow(new String[1]);
            dgvAviao.setValueAt(aviao.getAviID(), contador, 0);
            dgvAviao.setValueAt(aviao.getAviFabricante(), contador, 1);
            dgvAviao.setValueAt(aviao.getAviModelo(), contador, 2);
            contador++;
        }

        try {
            //Limpa o campo Código do Aviao
            txtCodigoAvi.setText(null);
            //Posiciona o cursor do mouse no campo Modelo do aviao
            txtModeloAvi.requestFocus();
            //Chama o método fecharBD da classe AviaoDAL
            dal.fecharBD();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro Na Conexão. Verifique com o Administrador do Banco de Dados !!!!");
        }
    }//GEN-LAST:event_btnMostrarTodosAviActionPerformed

    private void btnLimparAviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparAviActionPerformed
        //Limpa os campos do formulário e do grid ou tabela
        btnIncluirAvi.setEnabled(true);
        btnAlterarAvi.setEnabled(false);
        btnExcluirAvi.setEnabled(false);
        btnMostrarTodosAvi.setEnabled(true);
        txtCodigoAvi.setText(null);
        txtFabricanteAvi.setText("");
        txtModeloAvi.setText("");
        DefaultTableModel tabm = (DefaultTableModel) dgvAviao.getModel();
        for (int contador = tabm.getRowCount() - 1; contador >= 0; contador--) {
            tabm.removeRow(contador);
        }
    }//GEN-LAST:event_btnLimparAviActionPerformed

    private void btnSairAviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairAviActionPerformed
        // Fecha o formulário de Aviões e volta para o formulário principal
        dispose();
    }//GEN-LAST:event_btnSairAviActionPerformed

    private void btnAlterarAviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarAviActionPerformed
        try {
            //Chama o m�todo abrirBD da classe AviaoDAL            
            dal.abrirBD();
            //Fazendo a valida��o dos dados, o m�todo isEmpty que devolve true se a String for vazia ou false se a mesma n�o estiver vazia
            if (txtCodigoAvi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo código do Avião está vazio !!!!");
                txtCodigoAvi.requestFocus();
            } else if (txtFabricanteAvi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo Fabricante do avião está vazio !!!!");
                txtFabricanteAvi.requestFocus();
            } else if (txtModeloAvi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "O campo Modelo do Avião está vazio !!!!");
                txtModeloAvi.requestFocus();
            } else {
                aviao.setAviID(Long.parseLong(txtCodigoAvi.getText()));
                aviao.setAviFabricante(txtFabricanteAvi.getText());
                aviao.setAviModelo(txtModeloAvi.getText());
                try {
                    //Chama o m�todo alterarAviao da Classe AviaoDAL
                    dal.alterarAviao(aviao);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erro Na Conexão. Verifique com o Administrador do Banco de Dados !!!!");
                }
                JOptionPane.showMessageDialog(null, "Avião " + aviao.getAviModelo() + " Alterado Com Sucesso !!!!");
                //Limpa os dados preenchidos nos campos de texto
                txtCodigoAvi.setText(null);
                txtFabricanteAvi.setText("");
                txtModeloAvi.setText("");
                txtCodigoAvi.requestFocus();
                btnMostrarTodosAvi.setEnabled(true);
                //Chama o m�todo fecharBD da classe AviaoDAL
                dal.fecharBD();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "O campo Modelo do Avião está  vazio !!!!");
            txtModeloAvi.requestFocus();
        }
    }//GEN-LAST:event_btnAlterarAviActionPerformed

    private void btnPesquisarAviIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarAviIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarAviIDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAviao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAviao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAviao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAviao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAviao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarAvi;
    private javax.swing.JButton btnExcluirAvi;
    private javax.swing.JButton btnIncluirAvi;
    private javax.swing.JButton btnLimparAvi;
    private javax.swing.JButton btnMostrarTodosAvi;
    private javax.swing.JButton btnPesquisarAviID;
    private javax.swing.JButton btnSairAvi;
    private javax.swing.JTable dgvAviao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigoAvi;
    private javax.swing.JTextField txtFabricanteAvi;
    private javax.swing.JTextField txtModeloAvi;
    // End of variables declaration//GEN-END:variables
    
    private void inserirIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconeAviao.png")));
    }
}
