/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package br.udf.ProvaA1_Aviao.UI;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author rapha
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        inserirIcone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblFundo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuAplicativo = new javax.swing.JMenu();
        itmSair = new javax.swing.JMenuItem();
        mnuCadastros = new javax.swing.JMenu();
        itmCadAviao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/udf/ProvaA1_Aviao/UI/aviaoFundo.png"))); // NOI18N

        mnuAplicativo.setMnemonic('f');
        mnuAplicativo.setText("Aplicativo Avião");

        itmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmSair.setMnemonic('x');
        itmSair.setText("Sair");
        itmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSairActionPerformed(evt);
            }
        });
        mnuAplicativo.add(itmSair);

        menuBar.add(mnuAplicativo);

        mnuCadastros.setText("Cadastros");

        itmCadAviao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadAviao.setText("Aviões");
        itmCadAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadAviaoActionPerformed(evt);
            }
        });
        mnuCadastros.add(itmCadAviao);

        menuBar.add(mnuCadastros);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iblFundo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iblFundo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja Sair do Sistema? ", "Aviões",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_itmSairActionPerformed

    private void itmCadAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadAviaoActionPerformed
        //Verfica se o formulário é nulo e está visivel
        if ((frmAviao == null) || (!frmAviao.isVisible())) {
            frmAviao = new frmAviao();
            frmAviao.setVisible(true);
        }
    }//GEN-LAST:event_itmCadAviaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iblFundo;
    private javax.swing.JMenuItem itmCadAviao;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAplicativo;
    private javax.swing.JMenu mnuCadastros;
    // End of variables declaration//GEN-END:variables

    private void inserirIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconeAviao.png")));
    }
    //Declarando o objeto formAviao
    private frmAviao frmAviao;
}
